# Generated by Django 4.1.7 on 2023-03-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapi", "0003_rename_user_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
