# Generated by Django 4.1.7 on 2023-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapi", "0004_customuser_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser", name="age", field=models.IntegerField(null=True),
        ),
    ]
