# Generated by Django 4.1.7 on 2023-03-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapi", "0005_alter_customuser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="allergies",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="drinker",
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="pregnant",
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="smoker",
            field=models.BooleanField(blank=True),
        ),
    ]
