# Generated by Django 4.1.7 on 2023-03-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authapi",
            "0007_alter_customuser_allergies_alter_customuser_drinker_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
